#include <furi.h>
#include <hello_world_icons.h>  // Generated by fbt from .png files in images folder

int32_t hello_world_app(void* p)
{
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello World !");
    furi_delay_ms(5000);
    
    return 0;
}
